# Generated by Django 5.1.6 on 2025-02-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_booking_booking_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.IntegerField(),
        ),
    ]
